kind: pipeline
type: docker
name: collect

steps:
- name: collect
  image: crinte/alpine
  environment:
    GIT_USER_EMAIL: 
      from_secret: GITEMAIL
    GIT_USER_NAME:
      from_secret: GITUSR
    GIT_USER_PWD:
      from_secret: GITPWD
  commands:
  - mkdir ./data
  - curl https://raw.githubusercontent.com/freefq/free/master/v2 > ./data/v2
  - git config --global user.email "$${GIT_USER_EMAIL}"
  - git config --global user.name "$${GIT_USER_NAME}"
  - git add --all
  - git commit -m "update data"
  - git remote add pu https://$${GIT_USER_NAME}:$${GIT_USER_PWD}@github.com/$${GIT_USER_NAME}/$${DRONE_REPO_NAME}.git
  - git push pu main


trigger:
  event:
  - cron
  - push